env: "local"
storage_path: "/home/runner/Go-REST-API-Advanced/cmd/db/urls.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "someUser321"
  password: "somePassword123"